import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, Dimensions, Image, Animated, Alert } from 'react-native';

const { height } = Dimensions.get('window');

const quotesArray = [
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { content: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { content: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "There is hope, even when your brain tells you there isn't.", author: "John Green"  },
  { content: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "Never bend your head. Always hold it high. Look the world straight in the eye.", author: "Helen Keller" },
  { content: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { content: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { content: "The best revenge is massive success.", author: "Frank Sinatra" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you.", author: "Steve Jobs" },
  { content: "People who are crazy enough to think they can change the world, are the ones who do.", author: "Rob Siltanen" },
  { content: "Failure will never overtake me if my determination to succeed is strong enough.", author: "Og Mandino" },
  { content: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { content: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
  { content: "Imagine your life is perfect in every respect; what would it look like?", author: "Brian Tracy" },
  { content: "We generate fears while we sit. We overcome them by action.", author: "Dr. Henry Link" },
  { content: "Whether you think you can or think you can’t, you’re right.", author: "Henry Ford" },
  { content: "Security is mostly a superstition. Life is either a daring adventure or nothing.", author: "Helen Keller" },
  { content: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
  { content: "Creativity is intelligence having fun.", author: "Albert Einstein" },
  { content: "What you lack in talent can be made up with desire, hustle and giving 110% all the time.", author: "Don Zimmer" },
  { content: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
  { content: "Develop an ‘Attitude of Gratitude’. Say thank you to everyone you meet for everything they do for you.", author: "Brian Tracy" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "To see what is right and not do it is a lack of courage.", author: "Confucius" },
  { content: "Reading is to the mind, as exercise is to the body.", author: "Brian Tracy" },
  { content: "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality.", author: "Brian Tracy" },
  { content: "The future belongs to the competent. Get good, get better, be the best!", author: "Brian Tracy" },
  { content: "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded.", author: "Jack Canfield" },
  { content: "Things work out best for those who make the best of how things work out.", author: "John Wooden" },
  { content: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { content: "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time.", author: "Michael Phelps" },
  { content: "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals.", author: "Michelle Obama" },
  { content: "Today’s accomplishments were yesterday’s impossibilities.", author: "Robert H. Schuller" },
  { content: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { content: "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don’t quit.", author: "Conrad Hilton" },
  { content: "If you don’t take risks, you will always work for someone who does.", author: "Nora Denzel" },
  { content: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { content: "Success is not final; failure is not fatal: It is the courage to continue that counts.", author: "Winston S. Churchill" },
  { content: "A good objective of leadership is to help those who are doing poorly to do well and to help those who are doing well to do even better.", author: "Jim Rohn" },
  { content: "If you genuinely want something, don’t wait for it – teach yourself to be impatient.", author: "Gurbaksh Chahal" },
  { content: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Anonymous" },
  { content: "The ones who are crazy enough to think they can change the world, are the ones who do.", author: "Anonymous" },
  { content: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { content: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
  { content: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { content: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { content: "The starting point of all achievement is desire.", author: "Napoleon Hill" },
  { content: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier" },
  { content: "Knowing is not enough; we must apply. Wishing is not enough; we must do.", author: "Johann Wolfgang Von Goethe" },
  { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { content: "I have not failed. I’ve just found 10,000 ways that won’t work.", author: "Thomas A. Edison" },
  { content: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
  { content: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { content: "Take up one idea. Make that one idea your life–think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success.", author: "Swami Vivekananda" },
  { content: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { content: "Stop chasing the money and start chasing the passion.", author: "Tony Hsieh" },
  { content: "All our dreams can come true if we have the courage to pursue them.", author: "Walt Disney" },
  { content: "If you set your goals ridiculously high and it’s a failure, you will fail above everyone else’s success.", author: "James Cameron" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
  { content: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
  { content: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
  { content: "Success is not the absence of failure; it’s the persistence through failure.", author: "Aisha Tyler" },
  { content: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
  { content: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { content: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { content: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { content: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { content: "If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough.", author: "Oprah Winfrey" },
  { content: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
  { content: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { content: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { content: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { content: "May you live all the days of your life.", author: "Jonathan Swift" },
  { content: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen" },
  { content: "Do not let making a living prevent you from making a life.", author: "John Wooden" },
  { content: "Life is ours to be spent, not to be saved.", author: "D. H. Lawrence" },
  { content: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { content: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { content: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { content: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
  { content: "Good friends, good books, and a sleepy conscience: this is the ideal life.", author: "Mark Twain" },
  { content: "Life is ten percent what happens to us and ninety percent how we respond to it.", author: "Charles R. Swindoll" },
  { content: "I tell you, in this world being a little crazy helps to keep you sane.", author: "Zsa Zsa Gabor" },
  { content: "I have found that if you love life, life will love you back.", author: "Arthur Rubinstein" },
  { content: "Lighten up, just enjoy life, smile more, laugh more, and don’t get so worked up about things.", author: "Kenneth Branagh" },
  { content: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou" },
  { content: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
  { content: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { content: "Life is trying things to see if they work.", author: "Ray Bradbury" },
  { content: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
  { content: "Believe that life is worth living and your belief will help create the fact.", author: "William James" },
  { content: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
  { content: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
  { content: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { content: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { content: "May you live all the days of your life.", author: "Jonathan Swift" },
  { content: "Life itself is the most wonderful fairy tale.", author: "Hans Christian Andersen" },
  { content: "Do not let making a living prevent you from making a life.", author: "John Wooden" },
  { content: "Life is ours to be spent, not to be saved.", author: "D. H. Lawrence" },
  { content: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { content: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { content: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { content: "Life is what happens when you’re busy making other plans.", author: "John Lennon" },
  { content: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", author: "Albert Schweitzer" },
  { content: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { content: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
  { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { content: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
  { content: "It does not matter how slowly you go, so long as you do not stop.", author: "Confucius" },
  { content: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { content: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "The best revenge is massive success.", author: "Frank Sinatra" },
  { content: "If you can dream it, you can do it.", author: "Walt Disney" },
  { content: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
  { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { content: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
  { content: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { content: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "Whether you think you can or think you can’t, you’re right.", author: "Henry Ford" },
  { content: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { content: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t let what you cannot do interfere with what you can do.", author: "John R. Wooden" },
  { content: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { content: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
  { content: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { content: "Your present circumstances don’t determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Try to be a rainbow in someone’s cloud.", author: "Maya Angelou" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { content: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { content: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t let what you cannot do interfere with what you can do.", author: "John R. Wooden" },
  { content: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { content: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
  { content: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { content: "Your present circumstances don’t determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Try to be a rainbow in someone’s cloud.", author: "Maya Angelou" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { content: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { content: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t let what you cannot do interfere with what you can do.", author: "John R. Wooden" },
  { content: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { content: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
  { content: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { content: "Your present circumstances don’t determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Try to be a rainbow in someone’s cloud.", author: "Maya Angelou" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { content: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { content: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t let what you cannot do interfere with what you can do.", author: "John R. Wooden" },
  { content: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { content: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
  { content: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { content: "Your present circumstances don’t determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
  { content: "Try to be a rainbow in someone’s cloud.", author: "Maya Angelou" },
  { content: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { content: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
  { content: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
  { content: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
  { content: "You learn more from failure than from success. Don’t let it stop you. Failure builds character.", author: "Unknown" },
  { content: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { content: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { content: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "Act as if what you do makes a difference. It does.", author: "William James" },
  { content: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
  { content: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { content: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { content: "Don’t let what you cannot do interfere with what you can do.", author: "John R. Wooden" },
  { content: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { content: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { content: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { content: "If you can dream it, you can achieve it.", author: "Zig Ziglar" },
  { content: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
  { content: "Your present circumstances don’t determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { content: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
  { content: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { content: "We can’t help everyone, but everyone can help someone.", author: "Ronald Reagan" },
  { content: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
];

// Simple hash function to generate a seed from a string
const hashCode = (str) => {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0; // Convert to 32bit integer
  }
  return hash;
};

// Seeded pseudo-random number generator
const seededRandom = (seed) => {
  const x = Math.sin(seed++) * 10000;
  return x - Math.floor(x);
};

const getDailyQuote = () => {
  const today = new Date().toLocaleDateString(); // Get the current date in local string format
  const seed = hashCode(today);
  const randomIndex = Math.floor(seededRandom(seed) * quotesArray.length);
  return quotesArray[randomIndex];
};

const QuoteScreen = () => {
  const [quote, setQuote] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showGif, setShowGif] = useState(true);
  const fadeAnim = useState(new Animated.Value(1))[0];

  useEffect(() => {
    const dailyQuote = getDailyQuote();
    setQuote(dailyQuote);
    setLoading(false);

    const timer = setTimeout(() => {
      Animated.timing(fadeAnim, {
        toValue: 0,
        duration: 1000,
        useNativeDriver: true,
      }).start(() => setShowGif(false));
    }, 1800);

    return () => {
      clearTimeout(timer);
    };
  }, []);

  return (
    <View style={styles.container}>
      {showGif && (
        <Animated.View style={[styles.gifContainer, { opacity: fadeAnim }]}>
          <Image source={require('../assets/gold-glitter.gif')} style={styles.gif} />
        </Animated.View>
      )}
      {loading ? (
        <ActivityIndicator size="large" color="#0000ff" />
      ) : (
        <Animated.View style={styles.quoteContainer}>
          <Text style={styles.quoteText}>“{quote.content}”</Text>
          <Text style={styles.quoteAuthor}>- {quote.author}</Text>
        </Animated.View>
      )}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#7bbbef',
  },
  gifContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  gif: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  quoteContainer: {
    padding: 18,
    backgroundColor: '#7bbbef',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1.5,
    shadowRadius: 9,
    elevation: 1,
  },
  quoteText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#004aad',
    textAlign: 'center',
    marginBottom: 10,
  },
  quoteAuthor: {
    fontSize: 18,
    textAlign: 'center',
    color: '#004aad',
  },
});

export default QuoteScreen;