import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ActivityIndicator, Dimensions, Image, Animated, Alert } from 'react-native';

// Get the device's screen height
const { height } = Dimensions.get('window');

// Array of quotes to be displayed
const quotesArray = [
  // Each object contains a quote and the author
  { "content": "An idea holds little value without the motivation to bring it to life.", "author": "Jessica Schmilovich" },
  { "content": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
  { "content": "Great things are not done by impulse but by a series of small things brought together.", "author": "Vincent Van Gogh" },
  { "content": "In the middle of every difficulty lies opportunity.", "author": "Albert Einstein" },
  { "content": "The best way to predict the future is to create it.", "author": "Peter Drucker" },
  { "content": "Life's under no obligation to give us what we expect.", "author": "Margaret Mitchell" },
  { "content": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill" },
  { "content": "The only impossible journey is the one you never begin.", "author": "Tony Robbins" },
  { "content": "Blessed is he who expects nothing, for he shall never be disappointed.", "author": "Alexander Pope" },
  { "content": "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "author": "Jimmy Dean" },
  { "content": "The only way to discover the limits of the possible is to go beyond them into the impossible.", "author": "Arthur C. Clarke" },
  { "content": "Many people lose the small joys in the hope for the big happiness.", "author": "Pearl S. Buck" },
  { "content": "Your time is limited, don't waste it living someone else's life.", "author": "Steve Jobs" },
  { "content": "Faith is stepping out on nothing and landing on something.", "author": "Cornel West" },
  { "content": "Life is tough, my darling, but so are you.", "author": "Stephanie Bennett Henry" },
  { "content": "It is often in the darkest skies that we see the brightest stars.", "author": "Richard Evans" },
  { "content": "Remember, Hope is a good thing, maybe the best of things, and no good thing ever dies.", "author": "Stephen King" },
  { "content": "It's the possibility that keeps me going, not the guarantee.", "author": "Nicholas Sparks" },
  { "content": "Little things comfort us because little things distress us.", "author": "Blaise Pascal" },
  { "content": "As long as the sun’s shining, shit can’t be that bad.", "author": "J. Lynn" },
  { "content": "The power of attention is much greater than the force of self-restraint.", "author": "Charles Eisenstein" },
  { "content": "A change is brought about because ordinary people do extraordinary things.", "author": "Barack Obama" },
  { "content": "Sometimes good things fall apart so better things can fall together.", "author": "Marylin Monroe" },
  { "content": "It is never too late to be what you might have been.", "author": "George Eliot" },
  { "content": "I did then what I knew how to do. Now that I know better, I do better.", "author": "Maya Angelou" },
  { "content": "One love, one heart, one destiny.", "author": "Bob Marley" },
  { "content": "The first draft of anything is shit.", "author": "Ernest Hemingway" },
  { "content": "May your choices reflect your hopes, not your fears.", "author": "Nelson Mandela" },
  { "content": "Tomorrow doesn't matter, for all I have is today.", "author": "Horace" },
  { "content": "You have everything needed for the extravagant journey that is your life.", "author": "Carlos Castaneda" },
  { "content": "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather a lack of will.", "author": "Vince Lombardi" },
  { "content": "The road to success is not easy to navigate, but with hard work, drive, and passion, it's possible to achieve the American dream.", "author": "Tommy Hilfiger" },
  { "content": "I know who I am and who I may be if I choose.", "author": "Miguel de Cervantes Saavedra" },
  { "content": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson" },
  { "content": "Set your goals high and don't stop till you get there.", "author": "Bo Jackson" },
  { "content": "Though wrong gratifies in the moment, good yields its gifts over a lifetime.", "author": "Desmond Tutu" },
  { "content": "The willingness to do creates the ability to do.", "author": "Peter McWilliams" },
  { "content": "A year from now you may wish you had started today.", "author": "Karen Lamb" },
  { "content": "If there is no enemy within, the enemy outside cannot harm us.", "author": "African Proverb" },
  { "content": "Even if you are on the right track, you'll get run over if you just sit there.", "author": "Will Rogers" },
  { "content": "Age is no barrier. It's a limitation you put on your mind.", "author": "Jackie Joyner-Kersee" },
  { "content": "Happiness is not a destination or an experience. It's a decision.", "author": "Carlos Santana" },
  { "content": "We can evade reality, but we cannot evade the consequences of evading reality.", "author": "Ayn Rand" },
  { "content": "Freedom lies at the heart of my willingness to lose everything.", "author": "Alanis Morrisette" },
  { "content": "A man who dares to waste one hour of time has not discovered the value of life.", "author": "Charles Darwin" },
  { "content": "Be so good they can’t ignore you.", "author": "Steve Martin" },
  { "content": "To practice magic is to bear the responsibility for having a vision.", "author": "Starhawk" },
  { "content": "Nothing is impossible; the word itself says “I’m possible!", "author": "Audrey Hepburn" },
  { "content": "If you want to overcome the whole world, overcome yourself.", "author": "Fyodor Dostoevsky" },
  { "content": "Nothing is a waste of time if you use the experience wisely.", "author": "Auguste Rodin" },
  { "content": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale" },
  { "content": "People are afraid to die and even more afraid to live.", "author": "Sylvia Browne" },
  { "content": "Confidence is key; if you don't have it, fake it!", "author": "Lady Gaga" },
  { "content": "The future belongs to the risk-takers, not the comfort-seekers.", "author": "Brian Tracy" },
  { "content": "Once your awareness becomes a flame, it burns up the whole slavery that the mind has created.", "author": "Rajneesh" },
  { "content": "Because you are alive, everything is possible.", "author": "Thich Nhat Hanh" },
  { "content": "What we fear doing most is usually what we most need to do.", "author": "Tim Ferriss" },
  { "content": "You can't achieve anything in life without a small amount of sacrifice.", "author": "Shakira" },
  { "content": "There is nothing permanent except change.", "author": "Heraclitus" },
  { "content": "Courage is found in unlikely places.", "author": "J.R.R. Tolkien" },
  { "content": "Do—or do not. There is no try.", "author": "Yoda" },
  { "content": "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying ‘I will try again tomorrow.", "author": "Mary Anne Radmacher" },
  { "content": "All our dreams can come true if we have the courage to pursue them.", "author": "Walt Disney" },
  { "content": "Everything you've ever wanted is on the other side of fear.", "author": "George Addair" },
  { "content": "Heart is what separates the good from the great.", "author": "Michael Jordan" },
  { "content": "It's not the load that breaks you down, it's the way you carry it.", "author": "Lou Holtz" },
  { "content": "The best way out is always through.", "author": "Robert Frost" },
  { "content": "Inaction breeds doubt and fear. Action breeds confidence and success.", "author": "Dale Carnegie" },
  { "content": "Suddenly normal wasn't good enough.", "author": "Steven Kotler" },
  { "content": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt" },
  { "content": "Difficulties strengthen the mind as labor does the body.", "author": "Lucius Annaeus Seneca" },
  { "content": "Be so busy improving yourself that you have no time to criticize others.", "author": "Chetan Bhagat" },
  { "content": "The harder the conflict, the more glorious the triumph.", "author": "Thomas Paine" },
  { "content": "Courage is the art of being the only one who knows you’re scared to death.", "author": "Harold Wilson" },
  { "content": "The will must be stronger than the skill.", "author": "Muhammad Ali" },
  { "content": "Life is the sum of all your choices.", "author": "Albert Camus" },
  { "content": "Remember that failure is an event, not a person.", "author": "Unknown" },
  { "content": "This is your world. Shape it or someone else will.", "author": "Gary Lew" },
  { "content": "The secret to happiness is freedom … and the secret to freedom is courage.", "author": "Thucydides" },
  { "content": "Never cut what you can untie.", "author": "Joseph Joubert" },
  { "content": "Out of suffering have emerged the strongest souls; the most massive characters are seared with scars.", "author": "Kahlil Gibran" },
  { "content": "Do what you think is right. Don't let people make the decision of right or wrong for you.", "author": "Steve Maraboli" },
  { "content": "Fate whispers to the warrior ‘You can not withstand the storm.’ The warrior whispers back ‘I am the storm.'", "author": "Jake Remington" },
  { "content": "Honesty is the foundation of all good character.", "author": "John Wooden" },
  { "content": "Fear is a natural reaction to moving closer to the truth.", "author": "Pema Chödrön" },
  { "content": "To put everything in balance is good, to put everything in harmony is better.", "author": "Victor Hugo" },
  { "content": "This too shall pass.", "author": "Persian Adage" },
  { "content": "It takes courage and strength to admit the truth.", "author": "Rick Reordan" },
  { "content": "You wear a mask for so long you forget who you were beneath it.", "author": "Alan Moore" },
  { "content": "Self-deception is the enemy within.", "author": "Bill Wilson" },
  { "content": "Honesty – the best of all lost arts.", "author": "Mark Twain" },
  { "content": "Man needs difficulties, they are necessary for health.", "author": "Carl Gustav Jung" },
  { "content": "Error is the price we pay for progress.", "author": "Alfred North Whitehead" },
  { "content": "Don’t explain your philosophy. Embody it.", "author": "Epictetus" },
  { "content": "By stepping outside ourselves we gain perspective.", "author": "Jamie Wheal" },
  { "content": "A harmful truth is better than a useful lie.", "author": "Thomas Mann" },
  { "content": "Only great pain is the ultimate liberator of the spirit.", "author": "Friedrich Nietzsche" },
  { "content": "If honesty were suddenly introduced into American life, the whole system would collapse.", "author": "George Carlin" },
  { "content": "The way you think determines the way you live.", "author": "Tyson Yukaporta" },
  { "content": "You can be only afraid of what you think you know.", "author": "Jiddu Krishnamurti" },
  { "content": "Pessimism leads to weakness, optimism leads to power.", "author": "William James" },
  { "content": "Doubt can only be removed by action.", "author": "Goethe" },
  { "content": "Everything I’ve ever let go of has claw marks on it.", "author": "David Foster Wallace" },
  { "content": "True words are not pleasant, pleasant words are not true.", "author": "Lao Tzu" },
  { "content": "We cannot live better than in seeking to become better.", "author": "Socrates" },
  { "content": "The temptation to quit will be the greatest just before you are about to succeed.", "author": "Chinese Proverb" },
  { "content": "You don’t grow when you are comfortable.", "author": "Unknown" },
  { "content": "It is not the mountain we conquer but ourselves.", "author": "Sir Edmund Hillary" },
  { "content": "Harmony is the combination of opposites.", "author": "Aristotle" },
  { "content": "To hell with circumstances; I create opportunities.", "author": "Bruce Lee" },
  { "content": "To be native to a place we must learn to speak its language.", "author": "Robin Wall Kimmerer" },
  { "content": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde" },
  { "content": "What is necessary to change a person is to change his awareness of himself.", "author": "Abraham Maslow" },
  { "content": "Remember that wherever your heart is, there you will find your treasure.", "author": "Paulo Coelho" },
  { "content": "The difference between a successful person and others is not lack of strength, not lack of knowledge, but rather a lack of will.", "author": "Vince Lombardi" },
  { "content": "I know who I am and who I may be if I choose.", "author": "Miguel de Cervantes Saavedra" },
  { "content": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson" },
  { "content": "Set your goals high and don't stop till you get there.", "author": "Bo Jackson" },
  { "content": "Though wrong gratifies in the moment, good yields its gifts over a lifetime.", "author": "Desmond Tutu" },
  { "content": "The willingness to do creates the ability to do.", "author": "Peter McWilliams" },
  { "content": "A year from now you may wish you had started today.", "author": "Karen Lamb" },
  { "content": "If there is no enemy within, the enemy outside cannot harm us.", "author": "African Proverb" },
  { "content": "Even if you are on the right track, you'll get run over if you just sit there.", "author": "Will Rogers" },
  { "content": "Age is no barrier. It's a limitation you put on your mind.", "author": "Jackie Joyner-Kersee" },
  { "content": "Happiness is not a destination or an experience. It's a decision.", "author": "Carlos Santana" },
  { "content": "We can evade reality, but we cannot evade the consequences of evading reality.", "author": "Ayn Rand" },
  { "content": "Freedom lies at the heart of my willingness to lose everything.", "author": "Alanis Morrisette" },
  { "content": "A man who dares to waste one hour of time has not discovered the value of life.", "author": "Charles Darwin" },
  { "content": "Be so good they can’t ignore you.", "author": "Steve Martin" },
  { "content": "To practice magic is to bear the responsibility for having a vision.", "author": "Starhawk" },
  { "content": "Nothing is impossible; the word itself says “I’m possible!", "author": "Audrey Hepburn" },
  { "content": "If you want to overcome the whole world, overcome yourself.", "author": "Fyodor Dostoevsky" },
  { "content": "Nothing is a waste of time if you use the experience wisely.", "author": "Auguste Rodin" },
  { "content": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale" },
  { "content": "People are afraid to die and even more afraid to live.", "author": "Sylvia Browne" },
  { "content": "Confidence is key; if you don't have it, fake it!", "author": "Lady Gaga" },
  { "content": "The future belongs to the risk-takers, not the comfort-seekers.", "author": "Brian Tracy" },
  { "content": "Once your awareness becomes a flame, it burns up the whole slavery that the mind has created.", "author": "Rajneesh" },
  { "content": "Because you are alive, everything is possible.", "author": "Thich Nhat Hanh" },
  { "content": "What we fear doing most is usually what we most need to do.", "author": "Tim Ferriss" },
  { "content": "You can't achieve anything in life without a small amount of sacrifice.", "author": "Shakira" },
  { "content": "There is nothing permanent except change.", "author": "Heraclitus" },
  { "content": "Integrity is the essence of everything successful.", "author": "R. Buckminster Fuller" },
  { "content": "Values are like fingerprints. Nobody's are the same but you leave 'em all over everything you do.", "author": "Elvis Presley" },
  { "content": "If it is not right, do not do it; if it is not true, do not say it.", "author": "Marcus Aurelius" },
  { "content": "Don’t try to be different. Just be good. To be good is different enough.", "author": "Arthur Freed" },
  { "content": "Integrity is doing the right thing even when no one is watching.", "author": "C.S. Lewis" },
  { "content": "Wisdom is knowing what to do next; virtue is doing it.", "author": "David Star Jordan" },
  { "content": "The time is always right to do what is right.", "author": "Martin Luther King Jr." },
  { "content": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr." },
  { "content": "Treat all as your own self. Do not have a double standard.", "author": "Sathya Sai Baba" },
  { "content": "The act of acting morally is behaving as if everything we do matters.", "author": "Gloria Steinem" },
  { "content": "Be not merely good. Be good for something.", "author": "Henry David Thoreau" },
  { "content": "In the end, you should always do the right thing even if it’s hard.", "author": "Nicholas Sparks" },
  { "content": "You’re not everything you could be and you know it.", "author": "Jordan Peterson" },
  { "content": "When the whole world is silent, even one voice becomes powerful.", "author": "Malala Yousafzai" },
  { "content": "Ability may get you to the top, but it takes character to keep you there.", "author": "Stevie Wonder" },
  { "content": "If you can't do the little things right, you will never do the big things right.", "author": "William H. McRaven" },
  { "content": "If you don't stand for something, you will fall for anything.", "author": "Malcolm X" },
  { "content": "My only weapon is the question.", "author": "Jorge Ramos" },
  { "content": "An abnormal reaction to an abnormal situation is normal behaviour.", "author": "Viktor Frankl" },
  { "content": "The quality of a leader is reflected in the standards they set for themselves.", "author": "Ray Kroc" },
  { "content": "Knowing what must be done does away with fear.", "author": "Rosa Parks" },
  { "content": "The only thing you ever have to offer is you.", "author": "Mathew McConaughey" },
  { "content": "Rather fail with honor than succeed by fraud.", "author": "Sophocles" },
  { "content": "When I have listened to my mistakes, I have grown.", "author": "Hugh Prather" },
  { "content": "Don’t cheat the world of your contribution. Give it what you’ve got.", "author": "Steven Pressfield" },
  { "content": "Your great strength is knowing who you are.", "author": "Oscar de la Renta" },
  { "content": "Ride the energy of your own unique spirit.", "author": "Gabrielle Roth" },
  { "content": "The longer I live, the more beautiful life becomes.", "author": "Frank Lloyd Wright" },
  { "content": "Be not afraid of growing slowly; be only afraid of standing still.", "author": "Chinese proverb" },
  { "content": "Don’t compromise yourself. It’s all you’ve got.", "author": "Janis Jopin" },
  { "content": "Knowing oneself comes from attending with compassionate curiosity to what is happening within.", "author": "Gabor Mate" },
  { "content": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett" },
  { "content": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh" },
  { "content": "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett" },
  { "content": "We must accept finite disappointment, but never lose infinite hope.", "author": "Martin Luther King Jr." },
  { "content": "The best way to predict the future is to invent it.", "author": "Alan Kay" },
  { "content": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe" },
  { "content": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
  { "content": "Act as if what you do makes a difference. It does.", "author": "William James" },
  { "content": "The harder the conflict, the more glorious the triumph.", "author": "Thomas Paine" },
  { "content": "To succeed in life, you need two things: ignorance and confidence.", "author": "Mark Twain" },
  { "content": "Opportunities don't happen. You create them.", "author": "Chris Grosser" },
  { "content": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
  { "content": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill" },
  { "content": "The secret of success is to do the common thing uncommonly well.", "author": "John D. Rockefeller Jr." },
  { "content": "I attribute my success to this: I never gave or took any excuse.", "author": "Florence Nightingale" },
  { "content": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr." },
  { "content": "If you are not willing to risk the usual, you will have to settle for the ordinary.", "author": "Jim Rohn" },
  { "content": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson" },
  { "content": "The successful warrior is the average man, with laser-like focus.", "author": "Bruce Lee" },
  { "content": "You may have to fight a battle more than once to win it.", "author": "Margaret Thatcher" },
  { "content": "Life is 10% what happens to us and 90% how we react to it.", "author": "Charles R. Swindoll" },
  { "content": "Good, better, best. Never let it rest. 'Til your good is better and your better is best.", "author": "St. Jerome" },
  { "content": "A goal is a dream with a deadline.", "author": "Napoleon Hill" },
  { "content": "If you can't explain it simply, you don't understand it well enough.", "author": "Albert Einstein" },
  { "content": "If you think you can do a thing or think you can't do a thing, you're right.", "author": "Henry Ford" },
  { "content": "To handle yourself, use your head; to handle others, use your heart.", "author": "Eleanor Roosevelt" },
  { "content": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde" },
  { "content": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi" },
  { "content": "What we achieve inwardly will change outer reality.", "author": "Plutarch" },
  { "content": "There are no shortcuts to any place worth going.", "author": "Beverly Sills" },
  { "content": "Failure is the condiment that gives success its flavor.", "author": "Truman Capote" },
  { "content": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi" },
  { "content": "Motivation is what gets you started. Habit is what keeps you going.", "author": "Jim Ryun" },
  { "content": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius" },
  { "content": "Challenges are what make life interesting and overcoming them is what makes life meaningful.", "author": "Joshua J. Marine" },
  { "content": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman" },
  { "content": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis" },
  { "content": "Success is the result of preparation, hard work, and learning from failure.", "author": "Colin Powell" },
  { "content": "Your life does not get better by chance, it gets better by change.", "author": "Jim Rohn" },
  { "content": "The future belongs to those who prepare for it today.", "author": "Malcolm X" },
  { "content": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
  { "content": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein" },
  { "content": "A year from now you may wish you had started today.", "author": "Karen Lamb" },
  { "content": "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", "author": "Jordan Belfort" },
  { "content": "The best way out is always through.", "author": "Robert Frost" },
  { "content": "Dream big and dare to fail.", "author": "Norman Vaughan" },
  { "content": "You can't cross the sea merely by standing and staring at the water.", "author": "Rabindranath Tagore" },
  { "content": "Go confidently in the direction of your dreams. Live the life you have imagined.", "author": "Henry David Thoreau" },
  { "content": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
  { "content": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou" },
  { "content": "The best way to predict your future is to create it.", "author": "Peter Drucker" },
  { "content": "Nothing is impossible, the word itself says 'I'm possible!'", "author": "Audrey Hepburn" },
  { "content": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier" },
  { "content": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
  { "content": "Don't let yesterday take up too much of today.", "author": "Will Rogers" },
  { "content": "If you genuinely want something, don't wait for it—teach yourself to be impatient.", "author": "Gurbaksh Chahal" },
  { "content": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis" },
  { "content": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller" },
  { "content": "I never dreamed about success. I worked for it.", "author": "Estee Lauder" },
  { "content": "Opportunities don't happen. You create them.", "author": "Chris Grosser" },
  { "content": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
  { "content": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
  { "content": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett" },
  { "content": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh" },
  { "content": "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett" },
  { "content": "We must accept finite disappointment, but never lose infinite hope.", "author": "Martin Luther King Jr." },
  { "content": "The best way to predict the future is to invent it.", "author": "Alan Kay" },
  { "content": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe" },
  { "content": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
  { "content": "Act as if what you do makes a difference. It does.", "author": "William James" },
  { "content": "The harder the conflict, the more glorious the triumph.", "author": "Thomas Paine" },
  { "content": "To succeed in life, you need two things: ignorance and confidence.", "author": "Mark Twain" },
  { "content": "Opportunities don't happen. You create them.", "author": "Chris Grosser" },
  { "content": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
  { "content": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill" },
  { "content": "The secret of success is to do the common thing uncommonly well.", "author": "John D. Rockefeller Jr." },
  { "content": "I attribute my success to this: I never gave or took any excuse.", "author": "Florence Nightingale" },
  { "content": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr." },
  { "content": "If you are not willing to risk the usual, you will have to settle for the ordinary.", "author": "Jim Rohn" },
  { "content": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson" },
  { "content": "The successful warrior is the average man, with laser-like focus.", "author": "Bruce Lee" },
  { "content": "You may have to fight a battle more than once to win it.", "author": "Margaret Thatcher" },
  { "content": "Life is 10% what happens to us and 90% how we react to it.", "author": "Charles R. Swindoll" },
  { "content": "Good, better, best. Never let it rest. 'Til your good is better and your better is best.", "author": "St. Jerome" },
  { "content": "A goal is a dream with a deadline.", "author": "Napoleon Hill" },
  { "content": "If you can't explain it simply, you don't understand it well enough.", "author": "Albert Einstein" },
  { "content": "If you think you can do a thing or think you can't do a thing, you're right.", "author": "Henry Ford" },
  { "content": "To handle yourself, use your head; to handle others, use your heart.", "author": "Eleanor Roosevelt" },
  { "content": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde" },
  { "content": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi" },
  { "content": "What we achieve inwardly will change outer reality.", "author": "Plutarch" },
  { "content": "There are no shortcuts to any place worth going.", "author": "Beverly Sills" },
  { "content": "Failure is the condiment that gives success its flavor.", "author": "Truman Capote" },
  { "content": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi" },
  { "content": "Motivation is what gets you started. Habit is what keeps you going.", "author": "Jim Ryun" },
  { "content": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius" },
  { "content": "Challenges are what make life interesting and overcoming them is what makes life meaningful.", "author": "Joshua J. Marine" },
  { "content": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman" },
  { "content": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis" },
  { "content": "Success is the result of preparation, hard work, and learning from failure.", "author": "Colin Powell" },
  { "content": "Your life does not get better by chance, it gets better by change.", "author": "Jim Rohn" },
  { "content": "The future belongs to those who prepare for it today.", "author": "Malcolm X" },
  { "content": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
  { "content": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein" },
  { "content": "A year from now you may wish you had started today.", "author": "Karen Lamb" },
  { "content": "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", "author": "Jordan Belfort" },
  { "content": "The best way out is always through.", "author": "Robert Frost" },
  { "content": "Dream big and dare to fail.", "author": "Norman Vaughan" },
  { "content": "You can't cross the sea merely by standing and staring at the water.", "author": "Rabindranath Tagore" },
  { "content": "Go confidently in the direction of your dreams. Live the life you have imagined.", "author": "Henry David Thoreau" },
  { "content": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
  { "content": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou" },
  { "content": "The best way to predict your future is to create it.", "author": "Peter Drucker" },
  { "content": "Nothing is impossible, the word itself says 'I'm possible!'", "author": "Audrey Hepburn" },
  { "content": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier" },
  { "content": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
  { "content": "Don't let yesterday take up too much of today.", "author": "Will Rogers" },
  { "content": "If you genuinely want something, don't wait for it—teach yourself to be impatient.", "author": "Gurbaksh Chahal" },
  { "content": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis" },
  { "content": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller" },
  { "content": "I never dreamed about success. I worked for it.", "author": "Estee Lauder" },
  { "content": "Opportunities don't happen. You create them.", "author": "Chris Grosser" },
  { "content": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
  { "content": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
  { "content": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett" },
  { "content": "The only way to achieve the impossible is to believe it is possible.", "author": "Charles Kingsleigh" },
  { "content": "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett" },
  { "content": "We must accept finite disappointment, but never lose infinite hope.", "author": "Martin Luther King Jr." },
  { "content": "The best way to predict the future is to invent it.", "author": "Alan Kay" },
  { "content": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe" },
  { "content": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
  { "content": "Act as if what you do makes a difference. It does.", "author": "William James" },
  { "content": "The harder the conflict, the more glorious the triumph.", "author": "Thomas Paine" },
  { "content": "To succeed in life, you need two things: ignorance and confidence.", "author": "Mark Twain" },
  { "content": "Opportunities don't happen. You create them.", "author": "Chris Grosser" },
  { "content": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
  { "content": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill" },
  { "content": "The secret of success is to do the common thing uncommonly well.", "author": "John D. Rockefeller Jr." },
  { "content": "I attribute my success to this: I never gave or took any excuse.", "author": "Florence Nightingale" },
  { "content": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr." },
  { "content": "If you are not willing to risk the usual, you will have to settle for the ordinary.", "author": "Jim Rohn" },
  { "content": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson" },
  { "content": "The successful warrior is the average man, with laser-like focus.", "author": "Bruce Lee" },
  { "content": "You may have to fight a battle more than once to win it.", "author": "Margaret Thatcher" },
  { "content": "Life is 10% what happens to us and 90% how we react to it.", "author": "Charles R. Swindoll" },
  { "content": "Good, better, best. Never let it rest. 'Til your good is better and your better is best.", "author": "St. Jerome" },
  { "content": "A goal is a dream with a deadline.", "author": "Napoleon Hill" },
  { "content": "If you can't explain it simply, you don't understand it well enough.", "author": "Albert Einstein" },
  { "content": "If you think you can do a thing or think you can't do a thing, you're right.", "author": "Henry Ford" },
  { "content": "To handle yourself, use your head; to handle others, use your heart.", "author": "Eleanor Roosevelt" },
  { "content": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde" },
  { "content": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi" },
  { "content": "What we achieve inwardly will change outer reality.", "author": "Plutarch" },
  { "content": "There are no shortcuts to any place worth going.", "author": "Beverly Sills" },
  { "content": "Failure is the condiment that gives success its flavor.", "author": "Truman Capote" },
  { "content": "It's not whether you get knocked down, it's whether you get up.", "author": "Vince Lombardi" },
  { "content": "Motivation is what gets you started. Habit is what keeps you going.", "author": "Jim Ryun" },
  { "content": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius" },
  { "content": "Challenges are what make life interesting and overcoming them is what makes life meaningful.", "author": "Joshua J. Marine" },
  { "content": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman" },
  { "content": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis" },
  { "content": "Success is the result of preparation, hard work, and learning from failure.", "author": "Colin Powell" },
  { "content": "Your life does not get better by chance, it gets better by change.", "author": "Jim Rohn" },
  { "content": "The future belongs to those who prepare for it today.", "author": "Malcolm X" },
  { "content": "Don't judge each day by the harvest you reap but by the seeds that you plant.", "author": "Robert Louis Stevenson" },
  { "content": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein" },
  { "content": "A year from now you may wish you had started today.", "author": "Karen Lamb" },
  { "content": "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", "author": "Jordan Belfort" },
  { "content": "The best way out is always through.", "author": "Robert Frost" },
  { "content": "Dream big and dare to fail.", "author": "Norman Vaughan" },
  { "content": "You can't cross the sea merely by standing and staring at the water.", "author": "Rabindranath Tagore" },
  { "content": "Go confidently in the direction of your dreams. Live the life you have imagined.", "author": "Henry David Thoreau" },
  { "content": "Life is what happens when you're busy making other plans.", "author": "John Lennon" },
  { "content": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou" },
  { "content": "The best way to predict your future is to create it.", "author": "Peter Drucker" },
  { "content": "Nothing is impossible, the word itself says 'I'm possible!'", "author": "Audrey Hepburn" },
  { "content": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier" },
  { "content": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
  { "content": "Don't let yesterday take up too much of today.", "author": "Will Rogers" },
  { "content": "If you genuinely want something, don't wait for it—teach yourself to be impatient.", "author": "Gurbaksh Chahal" },
  { "content": "The road to success and the road to failure are almost exactly the same.", "author": "Colin R. Davis" },
  { "content": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller" },
  { "content": "I never dreamed about success. I worked for it.", "author": "Estee Lauder" },
  { "content": "Opportunities don't happen. You create them.", "author": "Chris Grosser" },
  { "content": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
  { "content": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi" },
  { "content": "Do not wait to strike till the iron is hot; but make it hot by striking.", "author": "William Butler Yeats" },
  { "content": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt" },
  { "content": "Action is the foundational key to all success.", "author": "Pablo Picasso" },
  { "content": "The future depends on what we do in the present.", "author": "Mahatma Gandhi" },
  { "content": "It is never too late to be what you might have been.", "author": "George Eliot" },
  { "content": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt" },
  { "content": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau" },
  { "content": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson" },
  { "content": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis" },
  { "content": "Start where you are. Use what you have. Do what you can.", "author": "Arthur Ashe" },
  { "content": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "author": "Ralph Waldo Emerson" },
  { "content": "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", "author": "Jimmy Dean" },
  { "content": "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", "author": "Albert Schweitzer" },
  { "content": "The secret of getting ahead is getting started.", "author": "Mark Twain" },
  { "content": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius" },
  { "content": "Our greatest glory is not in never falling, but in rising every time we fall.", "author": "Confucius" },
  { "content": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi" },
  { "content": "Keep your face always toward the sunshine—and shadows will fall behind you.", "author": "Walt Whitman" },
  { "content": "The best revenge is massive success.", "author": "Frank Sinatra" },
  { "content": "It always seems impossible until it's done.", "author": "Nelson Mandela" },
  { "content": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson" },
  { "content": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt" },
  { "content": "To live a creative life, we must lose our fear of being wrong.", "author": "Joseph Chilton Pearce" },
  { "content": "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author": "Aristotle" },
  { "content": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon" },
  { "content": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller" },
  { "content": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett" },
  { "content": "Success is not in what you have, but who you are.", "author": "Bo Bennett" },
  { "content": "Your time is limited, don't waste it living someone else's life.", "author": "Steve Jobs" },
  { "content": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney" },
  { "content": "If you really look closely, most overnight successes took a long time.", "author": "Steve Jobs" },
  { "content": "You miss 100% of the shots you don't take.", "author": "Wayne Gretzky" },
  { "content": "I've missed more than 9,000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game-winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.", "author": "Michael Jordan" },
  { "content": "If you're going through hell, keep going.", "author": "Winston Churchill" },
  { "content": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill" },
  { "content": "The road to success is always under construction.", "author": "Lily Tomlin" },
  { "content": "The only way to do great work is to love what you do.", "author": "Steve Jobs" },
  { "content": "Failure is simply the opportunity to begin again, this time more intelligently.", "author": "Henry Ford" },
  { "content": "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett" },
  { "content": "The purpose of our lives is to be happy.", "author": "Dalai Lama" },
  { "content": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius" },
  { "content": "You are never too old to set another goal or to dream a new dream.", "author": "C.S. Lewis" },
  { "content": "Your life does not get better by chance, it gets better by change.", "author": "Jim Rohn" },
  { "content": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson" },
  { "content": "To succeed in life, you need two things: ignorance and confidence.", "author": "Mark Twain" },
  { "content": "What you do today can improve all your tomorrows.", "author": "Ralph Marston" },
  { "content": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein" },
  { "content": "The best way to predict your future is to create it.", "author": "Peter Drucker" },
  { "content": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis" },
];

// Function to generate a unique daily seed based on the current date
const getDailySeed = () => {
  const today = new Date();
  // Calculate the current day of the year and multiply it by the current year
  const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
  const year = today.getFullYear();
  return dayOfYear + year * 365; // Unique seed for each day
};

// A simple seeded random number generator
const seededRandom = (seed) => {
  // Using sine function to generate a pseudo-random number
  let x = Math.sin(seed) * 10000;
  return x - Math.floor(x);
};

// Function to get the daily quote based on the seeded random value
const getDailyQuote = () => {
  const seed = getDailySeed();
  const randomIndex = Math.floor(seededRandom(seed) * quotesArray.length); // Pick a random quote
  return quotesArray[randomIndex];
};

// The main component that displays the quote
const QuoteScreen = () => {
  const [quote, setQuote] = useState(null); // State to store the daily quote
  const [loading, setLoading] = useState(true); // State to manage the loading indicator
  const [showGif, setShowGif] = useState(true); // State to manage the visibility of the gif
  const fadeAnim = new Animated.Value(1); // Animated value for fading out the gif

  useEffect(() => {
    // Get the daily quote and stop loading
    const dailyQuote = getDailyQuote();
    setQuote(dailyQuote);
    setLoading(false);

    // Timer to fade out the gif after 1.8 seconds
    const timer = setTimeout(() => {
      Animated.timing(fadeAnim, {
        toValue: 0, // Fade to zero opacity
        duration: 1000, // 1-second duration for fading
        useNativeDriver: true,
      }).start(() => setShowGif(false)); // Hide the gif after fading
    }, 1800);

    // Clean up the timer when the component unmounts
    return () => {
      clearTimeout(timer);
    };
  }, []);

  return (
    <View style={styles.container}>
      {/* Show the gif while it is still visible */}
      {showGif && (
        <Animated.View style={[styles.gifContainer, { opacity: fadeAnim }]}>
          <Image source={require('../assets/gold-glitter.gif')} style={styles.gif} />
        </Animated.View>
      )}

      {/* Show a loading indicator while fetching the quote */}
      {loading ? (
        <ActivityIndicator size="large" color="#0000ff" />
      ) : (
        // Show the quote and author when loading is complete
        <Animated.View style={styles.quoteContainer}>
          <Text style={styles.quoteText}>“{quote.content}”</Text>
          <Text style={styles.quoteAuthor}>- {quote.author}</Text>
        </Animated.View>
      )}
    </View>
  );
};

// Styles for the Flip The Switch Quote of the Day page
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#7bbbef', // Background color for the container
  },
  gifContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1, // Keep the gif on top
  },
  gif: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover', // Make the gif cover the entire screen
  },
  quoteContainer: {
    padding: 18,
    backgroundColor: '#7bbbef',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1.5,
    shadowRadius: 9,
    elevation: 1,
  },
  quoteText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#004aad', // Color for the quote text
    textAlign: 'center',
    marginBottom: 10,
  },
  quoteAuthor: {
    fontSize: 18,
    textAlign: 'center',
    color: '#004aad', // Color for the author text
  },
});

export default QuoteScreen;